# Generated by Django 4.2.1 on 2023-06-02 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("follower", "0002_alter_userfollows_user"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="follower.UserFollows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
